name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via python) and cache team.'
runs: 
  using: 'composite'
  steps: 
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{runner.os}}-pip-${{ hashFiles('**/requirements.txt')}}
        restore-key: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit !='true'
      run: python -m pip install --upgrade pip 
      shell: bash